import { Geist, Geist_Mono, Archivo, Bricolage_Grotesque } from 'next/font/google'
import './globals.css'
import 'flowbite'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

const archivo = Archivo({
  variable: '--font-archivo',
  subsets: ['latin']
})
const bricolage = Bricolage_Grotesque({
  variable: '--font-bricolage_grotesque',
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} ${geistSans.variable} ${geistMono.variable} ${bricolage.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
